# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches-ignore:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:  
  label-branch-fixes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: contains(github.push.commits.*.message, "fix #")

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - name: extract message
        id: extract-message
        run: |
          echo ${{github.push.commits.0.message}}
          echo "::set-output name=TEST::hi"

      # Runs a set of commands using the runners shell
      - name: collect output
        run: echo ${{ steps.extract-message.outputs.TEST }}
          
