name: label fixed-on-branch

# Controls when the workflow will run
on:
  push:
    branches-ignore:
      - master

jobs:  
  extract:
    runs-on: ubuntu-latest

    outputs: 
      issues: ${{ steps.extract-message.outputs.issues }}

    steps:      
      - name: extract message
        id: extract-message
        run: |                    
          echo "::set-output name=issues::[" `echo "${{github.event.commits[0].message}}" | egrep -o "(fix|close)\s+#([0-9]+)" | egrep -o "[0-9]+" | tr "\n" ", "` "]"
 
  label-issues:
    runs-on: ubuntu-latest
    needs: extract
    strategy:
      matrix:
        issue: ${{fromJSON(needs.extract.outputs.issues)}}        
    
    steps:
     - name: label-issue
       uses: andymckay/labeler@master
       with:
         add-labels: "fixed-on-branch"
         repo-token: ${{ secrets.GITHUB_TOKEN }}
         issue-number: ${{ matrix.issue }}
    
 
          
