# This is a basic workflow to help you get started with Actions

name: label fixed-on-branch

# Controls when the workflow will run
on:
  push:
    branches-ignore:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:  
  extract:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs: 
      issues: ${{ steps.extract-message.outputs.issues }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - name: extract message
        id: extract-message
        run: |                    
          echo "::set-output name=issues::[" `echo "${{github.event.commits[0].message}}" | egrep -o "(fix|close)\s+#([0-9]+)" | egrep -o "[0-9]+" | tr "\n" ", "` "]"

      # Runs a set of commands using the runners shell
      - name: check output
        run: echo got ${{ steps.extract-message.outputs.issues }}
 
  label-issues:
    runs-on: ubuntu-latest
    needs: extract
    strategy:
      matrix:
        issue: ${{fromJSON(needs.extract.outputs.issues)}}        
    
    steps:
     - name: use-issue
       run: echo issue ${{ matrix.issue }}
    
 
          
